### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by dinobu** [masonyc/Xamarin.EnableKeyboardEffect#1]
Hi and thanks for sharing.  I havent had a chance to try it but from reading your wiki, it looks like only platform specific code change is required on iOS side.
Also, comment "write here" is confusing, feels like something is missing or need to be added here by whoever uses this effect, I'd suggest changing that to something like "enable EnableKeyboardEffect on iOS" or some better description

**Comment by masonyc** [comment]
Hi, thanks for the feedback, I have updated it.
