### ISSUE TITLE
Error "Xamarin.Forms targets have been imported multiple times.  Please check your project file and remove the duplicate import(s)." 

### ISSUE THREAD

**Issue by dinobu** [masonyc/Xamarin.EnableKeyboardEffect#4]
Adding Nuget at solution level results in "Xamarin.Forms targets have been imported multiple times.  Please check your project file and remove the duplicate import(s)." error, cannot build.

**Comment by masonyc** [comment]
Can you please upload a sample repo so i can test on?

**Comment by dinobu** [comment]
> 
> 
> Can you please upload a sample repo so i can test on?

Can't do that.  I am trying it on my work project which consists of Droid, iOS, UWP head projects and then few .NET Standard 2.0 projects.  Cant add the Nuget to any .NET Standard 2.0 projects at all.  If I try I see
`Detected package downgrade: Xamarin.Forms 3.2.0.871581 to 3.1.0.583944 ...`

then evenually
```
All packages and projects are compatible with .NETStandard, Version-v2.0.
Package restore failed.  Rolling back package changes for "My Project"
```

**Comment by masonyc** [comment]
> > Can you please upload a sample repo so i can test on?
> 
> Can't do that. I am trying it on my work project which consists of Droid, iOS, UWP head projects and then few .NET Standard 2.0 projects. Cant add the Nuget to any .NET Standard 2.0 projects at all. If I try I see
> `Detected package downgrade: Xamarin.Forms 3.2.0.871581 to 3.1.0.583944 ...`
> 
> then evenually
> 
> ```
> All packages and projects are compatible with .NETStandard, Version-v2.0.
> Package restore failed.  Rolling back package changes for "My Project"
> ```

The package was built under Xamarin.Forms version 3.2.0.871581, It's not compatible to any version below that. If you are not able to upgrade your xamarin.forms version, you are welcome to grab the code and put it in your project manually

**Comment by tmt242001** [comment]
@masonyc  can you lower the Xamarin.Forms to 3.0

**Comment by masonyc** [comment]
@tmt242001 I have downgrade it to xamarin forms 3.0, @dinobu it should work for you now if you using the v1.0.2 package

**Comment by dinobu** [comment]
> 
> 
> @tmt242001 I have downgrade it to xamarin forms 3.0, @dinobu it should work for you now if you using the v1.0.2 package

I was able now to add v1.02 but as soon as I do that, my Android project throws the error I described above in this issue

**Comment by tmt242001** [comment]
@dinobu did you deleted bin and obj folders before adding the reference.

**Comment by dinobu** [comment]
No, I have not.  bin and obj folders in Android platform proj?

**Comment by tmt242001** [comment]
@dinobu delete all the bin and obj in all projects.

**Comment by dinobu** [comment]
Deleted all bin and obj folders in all projects, closed solution, restarted VS4Mac, reloaded solution, right-click on solution > Build, same error in my Droid project

**Comment by masonyc** [comment]
1. Can you try build our nuget sample project? 2. Can you build your droid project without this package?

**Comment by dinobu** [comment]
I can build my project without any issues without your package.  As soon as I add your package, I started getting this error.
I tried first adding it to just my Android, iOS, and my Core project which contains all the views and I got the error.
Then I added it to all my projects, still have the error

I checked all my proj files and found in one of the droid projects that I have Xamarin.Forms targets and Xamarin.forms props pairs for both 3.0.0446417 and 3.1.0.583944 
I tried removing each pair to try both versions.  As all of other of my projects are using 3.1.0.583944, removing that resulted in XF002 error (different types of XF framework found).  So I removed 3.0.0446417 pair to have all project reference the 3.1.0.583944 version and I am back to XF001 error again.  I tried restarting IDE, reloading project, cleaning it, rebuilding it on project and solution level, always same issue, it complains about XF001 error

**Comment by masonyc** [comment]
@dinobu https://dvlup.com/2018/10/01/error-xf001-xamarin-forms-targets-have-been-imported-multiple-times/ can you please have a try on the above link?

**Comment by dinobu** [comment]
> 
> 
> @dinobu https://dvlup.com/2018/10/01/error-xf001-xamarin-forms-targets-have-been-imported-multiple-times/ can you please have a try on the above link?

My project has no  `project_name.nuget.props` and `project_name.nuget.targets` files.

What I see are 
```
project_name.nuget.g.props 
project_name.nuget.g.targets
project_name.nuget.cache
project_name.nuget.stamp
```

, so not sure how reliable is that article

**Comment by tmt242001** [comment]
@dinobu Is there possibility, for you to send us your solution, so we can try to fix it for you ?

**Comment by dinobu** [comment]
> 
> 
> @dinobu Is there possibility, for you to send us your solution, so we can try to fix it for you ?

Cannot do that.  I also tried same on Windows, and still having issue with Android project, same XF001

**Comment by tmt242001** [comment]
@dinobu  this does not seems to be a error related to this package.

**Comment by tmt242001** [comment]
@dinobu try https://lastexitcode.com/blog/2018/03/10/NuGetSupportInVisualStudioMac7-4/

**Comment by dinobu** [comment]
> @dinobu Is there possibility, for you to send us your solution, so we can try to fix it for you ?

Would you be open to share screen on hangouts to show you?
I think what is happening is that projects have dependencies.  So we have a Droid head project, then another Droid project that is used by this head project, let's call it 2Droid.
So, the structure is like this
Droid
2Droid
Netstadard1
Netstandard2
....

That is how projects look like.   On a fresh clone, my 2Droid project has XF 3.1.0.583944 props and targets.  However, after adding lib, my 2Droid proj gets also imported XF 3.0.0.446417 which is your minimal required version.  As a reslult, I end up with 2 XF imports in 2Droid proj file.
This results in XF001 error.
I tried removing one or the other XF inport, but his would then result in XF002 error

**Comment by tmt242001** [comment]
It's Saturday here. We'll do this next Monday

**Comment by dinobu** [comment]
> 
> 
> It's Saturday here. We'll do this next Monday

OK, sounds good.  Here is what I found, below is the screenshot of how my DroidProj and 2DroidProj look like BEFORE and AFTER adding EnableKeyboardEffect package.  I think this shows what happens, notice how AFTER it got added, how it modified 2nd Droid proj file

![enablekeyboardeffect-xf001-error](https://user-images.githubusercontent.com/40807298/49310938-99f35b80-f494-11e8-9717-0d907770ce71.png)

**Comment by tmt242001** [comment]
@dinobu you droid project is not converted to PackageReference(s). please convert all you platform projects to PackageReference(s). It should fix your issue. 

https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
https://blog.nuget.org/20180409/migrate-packages-config-to-package-reference.html
https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader
