### ISSUE TITLE
IOS - Shows thin strip at the bottom of the screen instead of entire keyboard

### ISSUE THREAD

**Issue by dinobu** [masonyc/Xamarin.EnableKeyboardEffect#6]
I managed to add the library to IOS without problems but when running it, I get the collapsed keyboard as per screenshot.  That itself is not a problem, the real problem is that the collapsed keyboard is missing the "arrow" button on the right that allows you to tap on it to hide the collapsed keyboard entirely or to long-tap on it to expand it to full keyboard.

<img width="859" alt="ios-keybaord bar" src="https://user-images.githubusercontent.com/40807298/49243066-4d8b1b80-f3c1-11e8-858b-0349e62a6ae2.png">

I dont have problem with this collapsed keyboard but it normally comes with the down pointing arrow button on the right which allows me to expand it or hide it entirely.  But using this effect removes that

<img width="887" alt="ios-collapsed-keyboard-with-arrow-button" src="https://user-images.githubusercontent.com/40807298/49243310-defa8d80-f3c1-11e8-8cc8-98cd9456d67c.png">

This is pretty much same issue you get by using custom renderers to hide keyboard like so:

```
    public class SoftkeyboardDisabledEntryRenderer : EntryRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            // Disabling the keyboard
            this.Control.InputView = new UIView();
        }
    } 

```

**Comment by masonyc** [comment]
Does this happen in a real device or emulator?

**Comment by dinobu** [comment]
> 
> 
> Does this happen in a real device or emulator?

Real iPad Air 2 device
