### ISSUE TITLE
In MainActivity - "Platform" doesnot exist

### ISSUE THREAD

**Issue by AshishInnovantes** [masonyc/Xamarin.EnableKeyboardEffect#9]
Hi,

While following the documentation i tried to add this in My MainActivity file
      "Xamarin.EnableKeyboardEffect.Platform.Droid.Effects.Init(this);"

its says **The type or namespace name "Platform" does not exist in  the namespace "Xamarin.EnableKeyboardEffect".**

Also their is no option for adding assembly reference. Please suggest if am missing anything or update the documentation.

**Comment by masonyc** [comment]
hi, try delete all the bin and obj folders under your project and do a clean and rebuild.

**Comment by AshishInnovantes** [comment]
No it didn't work, its still the same issue. Also i tried this in a new project but it still didn't work.
Here is the link of my app please check  "[App Link](https://github.com/AshishInnovantes/TestApp)"

**Comment by masonyc** [comment]
Hi, found the problem, change android compile version to Android 9.0 will solve the issue. I will update the setup guide.
![image](https://user-images.githubusercontent.com/18006944/55914205-a5bd0e80-5c3a-11e9-9195-111485ca10af.png)

**Comment by AshishInnovantes** [comment]
Yeps it worked 👍
